services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "88:88"
    depends_on:
      - db

  db:
    image: mysql:8.0.37
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactor
      MYSQL_USER: refactor
      MYSQL_PASSWORD: refactor
